// enforceAdmissibility tests (NV-BL-ADM-05 refuse-first, NV-BL-ADM-06
// build-stage drift refusal, NV-BL-SR-03 addendum on toolScope).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { initProject } from '#core/store/init.js';
import { walkTree } from '#core/store';
import { enforceAdmissibility, getRulesetToolScope } from '#admissibility';
import { getUmbrellaVersion } from '#ruleset';
import { runWithAdmissibilityGate } from '../../src/query/index.js';

async function scaffold() {
  const projectRoot = await mkdtemp(join(tmpdir(), 'rcf-admissibility-enforce-'));
  await initProject({ projectRoot, projectName: 'AdmissibilityEnforceTest' });
  return projectRoot;
}

test('enforceAdmissibility refuses when chain does not declare a ruleset version (NV-BL-ADM-06 missing)', async () => {
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  const verdict = await enforceAdmissibility({ tree });
  assert.equal(verdict.verdict, 'refuse');
  assert.ok(verdict.unresolved.some((f) => f.rule === 'NV-BL-ADM-06'));
  assert.equal(verdict.drift.drift, 'missing');
});

test('enforceAdmissibility refuses on behavioural drift (NV-BL-ADM-06)', async () => {
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  const verdict = await enforceAdmissibility({
    tree,
    chainRulesetVersion: '0.0.1-stale',
  });
  const drift = verdict.unresolved.find((f) => f.rule === 'NV-BL-ADM-06');
  assert.ok(drift, 'NV-BL-ADM-06 should refuse behavioural drift');
  assert.match(drift.message, /0\.0\.1-stale/);
  assert.equal(verdict.drift.drift, 'behavioural');
  assert.equal(verdict.verdict, 'refuse');
});

test('enforceAdmissibility applies recorded overrides per NV-BL-ADM-05 (passWithOverrides)', async () => {
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  const umbrellaVersion = await getUmbrellaVersion();
  // Author every AC with an explicit scope, then override NV-BL-ADM-02
  // findings for legacy ACs so we can isolate the override channel test.
  // The scaffold's ACs have no scope; we override NV-BL-ADM-02 across
  // the whole rule, which per the enforce contract passes them through.
  const verdict = await enforceAdmissibility({
    tree,
    chainRulesetVersion: umbrellaVersion,
    overrides: [
      { rule: 'NV-BL-ADM-02', reason: 'legacy chain, migration window applies', authoredBy: 'dave' },
      { rule: 'NV-BL-ADM-03', reason: 'legacy chain, migration window applies', authoredBy: 'dave' },
    ],
  });
  // With the scope findings masked and the ruleset version aligned, the
  // remaining verdict is either pass or passWithOverrides.
  assert.notEqual(verdict.verdict, 'refuse', `unexpected refuse: ${JSON.stringify(verdict.unresolved, null, 2)}`);
  if (verdict.appliedOverrides.length > 0) {
    assert.equal(verdict.verdict, 'passWithOverrides');
  }
});

test('enforceAdmissibility refuses NV-BL-ADM-04 findings even when a matching override is supplied (guardrail)', async () => {
  // The generic override channel MUST NOT cover source-comment markers
  // (ruling-sheet item 16). Even if a caller passes an override for
  // NV-BL-ADM-04, the guardrail leaves the finding unresolved. We simulate
  // this by injecting an ADM-04 finding via a tree with no other findings
  // -- we can't easily inject through the natural scan path in a
  // scaffold test, so this asserts the guardrail on `unresolved` when a
  // pre-built ADM-04 finding is threaded through the same function.
  //
  // enforceAdmissibility only generates ADM-02/03/06 findings itself; a
  // synthetic ADM-04 threaded via other means would still be visible in
  // an integrated pipeline. Directly cover the guardrail path by
  // verifying that no override applied to ADM-04 rule id passes through.
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  const umbrellaVersion = await getUmbrellaVersion();
  const verdict = await enforceAdmissibility({
    tree,
    chainRulesetVersion: umbrellaVersion,
    overrides: [
      // Broad legitimate overrides:
      { rule: 'NV-BL-ADM-02', reason: 'migration', authoredBy: 'dave' },
      { rule: 'NV-BL-ADM-03', reason: 'migration', authoredBy: 'dave' },
      // Attempted (illegitimate) marker override -- MUST have no effect
      // on findings generated by this function; enforce should not
      // accept it as covering an ADM-04 finding either.
      { rule: 'NV-BL-ADM-04', reason: 'attempted marker override', authoredBy: 'dave' },
    ],
  });
  // The verdict here should have no NV-BL-ADM-04 findings because
  // enforce does not emit them. What we assert: the ADM-04 override
  // supplied above did not spuriously mark itself as applied (guarded
  // by the guardrail on the ADM-04 branch).
  const appliedAdm04 = verdict.appliedOverrides.filter((o) => o.rule === 'NV-BL-ADM-04');
  assert.equal(appliedAdm04.length, 0, 'NV-BL-ADM-04 overrides must never be counted as applied via the generic channel');
});

test('getRulesetToolScope surfaces the ratified {chainAdmissibility, traceabilityAndQueryTools} block', async () => {
  const scope = await getRulesetToolScope();
  assert.equal(scope.chainAdmissibility, true);
  assert.equal(scope.traceabilityAndQueryTools, true);
});

test('runWithAdmissibilityGate short-circuits query when admissibility refuses (NV-BL-SR-03 addendum)', async () => {
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  let called = 0;
  const result = await runWithAdmissibilityGate({
    tree,
    chainRulesetVersion: '0.0.1-stale',
    produce: () => {
      called += 1;
      return { rows: [] };
    },
  });
  assert.equal(called, 0, 'produce() must not run when admissibility refuses');
  assert.equal(result.status, 'refused-admissibility');
  assert.match(result.refusal, /NV-BL-ADM-06/);
});

test('runWithAdmissibilityGate runs the query when admissibility passes with overrides', async () => {
  const projectRoot = await scaffold();
  const { tree } = await walkTree({ projectRoot });
  const umbrellaVersion = await getUmbrellaVersion();
  let called = 0;
  const result = await runWithAdmissibilityGate({
    tree,
    chainRulesetVersion: umbrellaVersion,
    overrides: [
      { rule: 'NV-BL-ADM-02', reason: 'migration', authoredBy: 'dave' },
      { rule: 'NV-BL-ADM-03', reason: 'migration', authoredBy: 'dave' },
    ],
    produce: () => {
      called += 1;
      return { rows: ['ok'] };
    },
  });
  assert.equal(called, 1);
  assert.equal(result.status, 'ok');
  assert.deepEqual(result.payload, { rows: ['ok'] });
});
